"""
Consistent Character Image Generator
=====================================
Script untuk menggenerate gambar dengan karakter yang konsisten
menggunakan Grok AI API endpoint.

Strategi konsistensi:
1. Generate karakter awal dengan deskripsi detail
2. Simpan deskripsi karakter sebagai "character profile"
3. Gunakan edit_image dengan gambar referensi untuk variasi pose/aksi
4. Selalu sertakan deskripsi karakter yang sama di setiap prompt

Author: Generated by Gemini
"""

import requests
import json
import re
import os
import uuid
from datetime import datetime
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import Optional, List, Tuple


# ============================================================================
# CONFIGURATION
# ============================================================================

API_URL = "http://localhost:8017/v1/chat/completions"
API_KEY = None  # Set if needed

# Output directories
OUTPUT_DIR = Path("generated_characters")
CHARACTERS_DIR = OUTPUT_DIR / "characters"
IMAGES_DIR = OUTPUT_DIR / "images"

# Create directories
OUTPUT_DIR.mkdir(exist_ok=True)
CHARACTERS_DIR.mkdir(exist_ok=True)
IMAGES_DIR.mkdir(exist_ok=True)


# ============================================================================
# DATA CLASSES
# ============================================================================

@dataclass
class CharacterProfile:
    """Profil karakter untuk konsistensi"""
    id: str
    name: str
    description: str
    appearance: str
    clothing: str
    style: str
    reference_image_url: Optional[str] = None
    reference_image_path: Optional[str] = None
    created_at: str = ""
    
    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.now().isoformat()
    
    def get_full_prompt(self) -> str:
        """Generate full prompt dengan deskripsi karakter"""
        return f"{self.description}. {self.appearance}. {self.clothing}. Style: {self.style}"
    
    def save(self, filepath: Path):
        """Simpan profil karakter ke file JSON"""
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(asdict(self), f, indent=2, ensure_ascii=False)
        print(f"✓ Character profile saved: {filepath}")
    
    @classmethod
    def load(cls, filepath: Path) -> 'CharacterProfile':
        """Load profil karakter dari file JSON"""
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return cls(**data)


# ============================================================================
# LOGGING UTILITIES
# ============================================================================

class Logger:
    """Simple tree-style logger"""
    
    @staticmethod
    def header(text: str):
        print(f"\n{'─' * 60}")
        print(f"🎨 {text.upper()}")
        print(f"{'─' * 60}")
    
    @staticmethod
    def step(text: str):
        print(f"├─ {text}")
    
    @staticmethod
    def success(text: str, **details):
        print(f"│  ├─ ✓ {text}")
        for key, value in details.items():
            print(f"│  │  ├─ {key}: {value}")
    
    @staticmethod
    def error(text: str, error: str = None):
        print(f"│  ├─ ✗ {text}")
        if error:
            print(f"│  │  └─ error: {error[:100]}")
    
    @staticmethod
    def info(key: str, value: str):
        print(f"│  │  ├─ {key}: {value}")


log = Logger()


# ============================================================================
# API FUNCTIONS
# ============================================================================

def generate_image(prompt: str, retries: int = 3) -> Optional[str]:
    """
    Generate image dari prompt menggunakan Grok API
    Returns: URL gambar atau None jika gagal
    """
    headers = {"Content-Type": "application/json"}
    if API_KEY:
        headers["Authorization"] = f"Bearer {API_KEY}"

    payload = {
        "model": "grok-imagine-0.9",
        "messages": [
            {
                "role": "user",
                "content": [{"type": "text", "text": prompt}]
            }
        ]
    }

    for attempt in range(1, retries + 1):
        try:
            response = requests.post(API_URL, headers=headers, json=payload, timeout=120)
            response.raise_for_status()
            result = response.json()

            if "choices" in result and len(result["choices"]) > 0:
                content = result["choices"][0]["message"]["content"]
                
                # Extract image URL dari response
                patterns = [
                    r'!\[Generated Image\]\((http://localhost:8017/images/[^)]+)\)',
                    r'src="(http://localhost:8017/images/[^"]+)"',
                    r'(http://localhost:8017/images/[^\s\)\"]+)',
                ]
                
                for pattern in patterns:
                    match = re.search(pattern, content)
                    if match:
                        return match.group(1).rstrip('"')
                
                log.error(f"No image URL found (attempt {attempt})")
            else:
                log.error(f"No content in response (attempt {attempt})")
                
        except requests.exceptions.RequestException as e:
            log.error(f"Request failed (attempt {attempt})", str(e))
        
        if attempt < retries:
            import time
            time.sleep(2)
    
    return None


def edit_image(prompt: str, image_url: str, retries: int = 3) -> Optional[str]:
    """
    Edit gambar dengan prompt menggunakan gambar referensi
    Returns: URL gambar baru atau None jika gagal
    """
    headers = {"Content-Type": "application/json"}
    if API_KEY:
        headers["Authorization"] = f"Bearer {API_KEY}"

    payload = {
        "model": "grok-4.1-thinking",
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {"type": "image_url", "image_url": {"url": image_url}}
                ]
            }
        ]
    }

    for attempt in range(1, retries + 1):
        try:
            response = requests.post(API_URL, headers=headers, json=payload, timeout=180)
            response.raise_for_status()
            result = response.json()

            if "choices" in result and len(result["choices"]) > 0:
                content = result["choices"][0]["message"]["content"]
                
                patterns = [
                    r'!\[Generated Image\]\((http://localhost:8017/images/[^)]+\.jpg)\)',
                    r'src="(http://localhost:8017/images/[^"]+\.jpg)"',
                    r'(http://localhost:8017/images/[^\s\)\"]+\.jpg)',
                ]
                
                for pattern in patterns:
                    match = re.search(pattern, content)
                    if match:
                        return match.group(1).rstrip('"')
                
                log.error(f"No image URL in response (attempt {attempt})")
            else:
                log.error(f"No content in response (attempt {attempt})")
                
        except requests.exceptions.RequestException as e:
            log.error(f"Request failed (attempt {attempt})", str(e))
        
        if attempt < retries:
            import time
            time.sleep(2)
    
    return None


def download_image(url: str, output_path: Path) -> bool:
    """Download gambar dari URL"""
    try:
        response = requests.get(url, stream=True, timeout=60)
        response.raise_for_status()
        
        with open(output_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        
        return True
    except Exception as e:
        log.error(f"Download failed: {e}")
        return False


# ============================================================================
# CHARACTER GENERATOR CLASS
# ============================================================================

class ConsistentCharacterGenerator:
    """
    Generator untuk membuat gambar dengan karakter yang konsisten.
    
    Workflow:
    1. create_character() - Buat profil karakter baru
    2. generate_reference() - Generate gambar referensi
    3. generate_variation() - Generate variasi dengan pose/aksi berbeda
    """
    
    def __init__(self):
        self.characters: dict[str, CharacterProfile] = {}
        self._load_existing_characters()
    
    def _load_existing_characters(self):
        """Load semua karakter yang sudah ada"""
        for json_file in CHARACTERS_DIR.glob("*.json"):
            try:
                char = CharacterProfile.load(json_file)
                self.characters[char.id] = char
                print(f"  Loaded character: {char.name} ({char.id})")
            except Exception as e:
                print(f"  Warning: Could not load {json_file}: {e}")
    
    def create_character(
        self,
        name: str,
        description: str,
        appearance: str,
        clothing: str,
        style: str = "high quality, detailed, professional"
    ) -> CharacterProfile:
        """
        Buat profil karakter baru.
        
        Args:
            name: Nama karakter (untuk referensi)
            description: Deskripsi umum (contoh: "A cute cartoon fox mascot")
            appearance: Detail penampilan (contoh: "orange fur, big blue eyes, fluffy tail")
            clothing: Pakaian karakter (contoh: "wearing a red hoodie and jeans")
            style: Gaya gambar (contoh: "3D render, Pixar style")
        
        Returns:
            CharacterProfile object
        """
        log.header(f"Creating Character: {name}")
        
        char_id = str(uuid.uuid4())[:8]
        
        character = CharacterProfile(
            id=char_id,
            name=name,
            description=description,
            appearance=appearance,
            clothing=clothing,
            style=style
        )
        
        # Save profile
        profile_path = CHARACTERS_DIR / f"{char_id}_{name.lower().replace(' ', '_')}.json"
        character.save(profile_path)
        
        self.characters[char_id] = character
        
        log.success(f"Character created", id=char_id, name=name)
        log.info("Full prompt", character.get_full_prompt()[:80] + "...")
        
        return character
    
    def generate_reference(self, character: CharacterProfile) -> Optional[str]:
        """
        Generate gambar referensi untuk karakter.
        Gambar ini akan digunakan sebagai basis untuk variasi selanjutnya.
        
        Args:
            character: CharacterProfile object
        
        Returns:
            URL gambar referensi atau None jika gagal
        """
        log.header(f"Generating Reference Image: {character.name}")
        
        # Prompt untuk referensi - fokus pada tampilan karakter yang jelas
        prompt = f"""Create a clear reference image of:
{character.get_full_prompt()}

Requirements:
- Full body visible
- Front facing view
- Neutral pose (standing)
- Clean simple background
- High quality detailed render"""
        
        log.step("Generating image...")
        log.info("Prompt", prompt[:100] + "...")
        
        image_url = generate_image(prompt)
        
        if image_url:
            # Download dan simpan
            filename = f"{character.id}_reference.jpg"
            output_path = IMAGES_DIR / filename
            
            if download_image(image_url, output_path):
                character.reference_image_url = image_url
                character.reference_image_path = str(output_path)
                
                # Update saved profile
                profile_path = CHARACTERS_DIR / f"{character.id}_{character.name.lower().replace(' ', '_')}.json"
                character.save(profile_path)
                
                log.success("Reference image generated", 
                           url=image_url[:60] + "...",
                           saved=str(output_path))
                return image_url
            else:
                log.error("Failed to download image")
        else:
            log.error("Failed to generate image")
        
        return None
    
    def generate_variation(
        self,
        character: CharacterProfile,
        action: str,
        background: str = "simple clean background",
        extra_details: str = ""
    ) -> Optional[Tuple[str, Path]]:
        """
        Generate variasi gambar dengan pose/aksi berbeda, 
        tetap mempertahankan konsistensi karakter.
        
        Args:
            character: CharacterProfile object
            action: Aksi/pose yang diinginkan (contoh: "running", "jumping", "waving")
            background: Latar belakang (contoh: "in a forest", "city street")
            extra_details: Detail tambahan
        
        Returns:
            Tuple (URL, Path) atau None jika gagal
        """
        log.header(f"Generating Variation: {character.name} - {action}")
        
        if not character.reference_image_url:
            log.error("No reference image! Generate reference first.")
            return None
        
        # Prompt untuk variasi - sertakan deskripsi karakter lengkap
        prompt = f"""Generate a new image of THE EXACT SAME CHARACTER shown in the reference image.

Character details (MUST MATCH):
{character.get_full_prompt()}

New scene:
- Action/Pose: {action}
- Background: {background}
{f"- Extra: {extra_details}" if extra_details else ""}

IMPORTANT: 
- Keep the character's appearance EXACTLY the same
- Same face, same body proportions, same colors
- Same clothing style
- Only change the pose/action and background"""
        
        log.step("Editing image with new pose...")
        log.info("Action", action)
        log.info("Background", background)
        
        new_image_url = edit_image(prompt, character.reference_image_url)
        
        if new_image_url:
            # Generate unique filename
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            safe_action = action.lower().replace(" ", "_")[:20]
            filename = f"{character.id}_{safe_action}_{timestamp}.jpg"
            output_path = IMAGES_DIR / filename
            
            if download_image(new_image_url, output_path):
                log.success("Variation generated",
                           url=new_image_url[:60] + "...",
                           saved=str(output_path))
                return new_image_url, output_path
            else:
                log.error("Failed to download image")
        else:
            log.error("Failed to generate variation")
        
        return None
    
    def generate_batch_variations(
        self,
        character: CharacterProfile,
        variations: List[dict]
    ) -> List[Tuple[str, Path]]:
        """
        Generate multiple variasi sekaligus.
        
        Args:
            character: CharacterProfile object
            variations: List of dicts with keys: action, background, extra_details
        
        Returns:
            List of (URL, Path) tuples untuk yang berhasil
        """
        log.header(f"Batch Generation: {character.name} ({len(variations)} variations)")
        
        results = []
        
        for i, var in enumerate(variations, 1):
            log.step(f"Variation {i}/{len(variations)}: {var.get('action', 'unknown')}")
            
            result = self.generate_variation(
                character,
                action=var.get("action", "standing"),
                background=var.get("background", "simple background"),
                extra_details=var.get("extra_details", "")
            )
            
            if result:
                results.append(result)
            
            # Delay antar request
            if i < len(variations):
                import time
                time.sleep(2)
        
        print(f"\n{'─' * 60}")
        print(f"✓ Completed: {len(results)}/{len(variations)} variations generated")
        print(f"{'─' * 60}")
        
        return results
    
    def get_character(self, char_id: str) -> Optional[CharacterProfile]:
        """Get character by ID"""
        return self.characters.get(char_id)
    
    def list_characters(self) -> List[CharacterProfile]:
        """List all available characters"""
        return list(self.characters.values())


# ============================================================================
# PREDEFINED VARIATIONS FOR MASS GENERATION
# ============================================================================

# Daftar aksi/pose yang bisa dikombinasi
ACTIONS = [
    "standing confidently with arms crossed",
    "waving hello with one hand raised",
    "running fast with dynamic pose",
    "jumping with joy, arms up",
    "sitting relaxed and comfortable",
    "walking casually forward",
    "dancing happily with rhythm",
    "sleeping peacefully curled up",
    "laughing out loud with head tilted",
    "thinking deeply with hand on chin",
    "pointing forward with finger",
    "giving thumbs up with big smile",
    "eating delicious food happily",
    "drinking from a cup",
    "reading a book intently",
    "writing or drawing on paper",
    "playing video games excited",
    "cooking in the kitchen",
    "exercising doing stretches",
    "meditating in peaceful pose",
    "taking a selfie with phone",
    "listening to music with headphones",
    "playing guitar or instrument",
    "painting on a canvas",
    "doing martial arts kick",
    "flying through the air superhero style",
    "swimming in water",
    "riding a bicycle",
    "skateboarding doing tricks",
    "playing sports with a ball",
]

# Daftar latar belakang
BACKGROUNDS = [
    "clean white studio background",
    "colorful abstract gradient background",
    "sunny park with green grass and trees",
    "cozy home living room",
    "modern city street with buildings",
    "beautiful beach with ocean waves",
    "magical forest with glowing lights",
    "futuristic space station",
    "cute bedroom with decorations",
    "professional office workspace",
    "restaurant or cafe interior",
    "school classroom setting",
    "concert stage with lights",
    "gym or fitness center",
    "shopping mall interior",
    "movie theater entrance",
    "hospital or clinic",
    "library with bookshelves",
    "museum or art gallery",
    "amusement park with rides",
    "rooftop with city skyline view",
    "garden with beautiful flowers",
    "snowy winter landscape",
    "autumn forest with falling leaves",
    "rainy day with umbrella",
    "sunset at the horizon",
    "starry night sky",
    "underwater scene with fish",
    "mountain peak landscape",
    "tropical jungle environment",
]

# Daftar ekspresi/emosi
EMOTIONS = [
    "happy and cheerful expression",
    "excited and energetic expression",
    "calm and peaceful expression",
    "determined and confident expression",
    "surprised and amazed expression",
    "curious and interested expression",
    "shy and blushing expression",
    "cool and stylish expression",
    "silly and playful expression",
    "romantic and dreamy expression",
]


# ============================================================================
# MASS GENERATION CLASS
# ============================================================================

class MassCharacterGenerator(ConsistentCharacterGenerator):
    """
    Extended generator untuk mass production gambar karakter konsisten.
    """
    
    def generate_mass_variations(
        self,
        character: CharacterProfile,
        num_images: int = 10,
        actions: List[str] = None,
        backgrounds: List[str] = None,
        emotions: List[str] = None,
        delay_seconds: float = 1.5
    ) -> List[Tuple[str, Path]]:
        """
        Generate banyak variasi gambar secara otomatis.
        
        Args:
            character: CharacterProfile object
            num_images: Jumlah gambar yang ingin di-generate
            actions: Custom list aksi (atau pakai default)
            backgrounds: Custom list background (atau pakai default)
            emotions: Custom list emosi (atau pakai default) 
            delay_seconds: Delay antar request untuk menghindari rate limit
        
        Returns:
            List of (URL, Path) tuples
        """
        import random
        import time
        
        log.header(f"MASS GENERATION: {character.name}")
        print(f"│  Target: {num_images} images")
        
        if not character.reference_image_url:
            log.error("No reference image! Generate reference first.")
            return []
        
        # Use provided lists or defaults
        action_list = actions or ACTIONS
        bg_list = backgrounds or BACKGROUNDS
        emotion_list = emotions or EMOTIONS
        
        results = []
        failed = 0
        
        for i in range(num_images):
            # Random combination
            action = random.choice(action_list)
            background = random.choice(bg_list)
            emotion = random.choice(emotion_list)
            
            print(f"\n├─ [{i+1}/{num_images}] Generating...")
            log.info("Action", action[:50])
            log.info("Background", background[:40])
            log.info("Emotion", emotion[:30])
            
            result = self.generate_variation(
                character,
                action=action,
                background=background,
                extra_details=emotion
            )
            
            if result:
                results.append(result)
                log.success(f"Image {i+1} complete", path=str(result[1].name))
            else:
                failed += 1
                log.error(f"Image {i+1} failed")
            
            # Delay untuk menghindari rate limit
            if i < num_images - 1:
                print(f"│  │  └─ Waiting {delay_seconds}s before next...")
                time.sleep(delay_seconds)
        
        # Summary
        print(f"\n{'═' * 60}")
        print(f"📊 MASS GENERATION COMPLETE")
        print(f"{'═' * 60}")
        print(f"   ✓ Success: {len(results)} images")
        print(f"   ✗ Failed:  {failed} images")
        print(f"   📁 Output: {IMAGES_DIR}")
        print(f"{'═' * 60}\n")
        
        return results
    
    def generate_all_actions(
        self,
        character: CharacterProfile,
        background: str = "clean white studio background",
        delay_seconds: float = 1.5
    ) -> List[Tuple[str, Path]]:
        """
        Generate karakter dengan SEMUA aksi yang tersedia (30 aksi).
        
        Args:
            character: CharacterProfile object
            background: Background yang sama untuk semua gambar
            delay_seconds: Delay antar request
        
        Returns:
            List of (URL, Path) tuples
        """
        import time
        
        log.header(f"ALL ACTIONS: {character.name}")
        print(f"│  Total actions: {len(ACTIONS)}")
        print(f"│  Background: {background}")
        
        if not character.reference_image_url:
            log.error("No reference image!")
            return []
        
        results = []
        
        for i, action in enumerate(ACTIONS, 1):
            print(f"\n├─ [{i}/{len(ACTIONS)}] {action[:40]}...")
            
            result = self.generate_variation(
                character,
                action=action,
                background=background
            )
            
            if result:
                results.append(result)
            
            if i < len(ACTIONS):
                time.sleep(delay_seconds)
        
        print(f"\n✓ Generated {len(results)}/{len(ACTIONS)} action images")
        return results
    
    def generate_all_backgrounds(
        self,
        character: CharacterProfile,
        action: str = "standing confidently",
        delay_seconds: float = 1.5
    ) -> List[Tuple[str, Path]]:
        """
        Generate karakter dengan SEMUA background yang tersedia (30 background).
        
        Args:
            character: CharacterProfile object  
            action: Aksi yang sama untuk semua gambar
            delay_seconds: Delay antar request
        
        Returns:
            List of (URL, Path) tuples
        """
        import time
        
        log.header(f"ALL BACKGROUNDS: {character.name}")
        print(f"│  Total backgrounds: {len(BACKGROUNDS)}")
        print(f"│  Action: {action}")
        
        if not character.reference_image_url:
            log.error("No reference image!")
            return []
        
        results = []
        
        for i, bg in enumerate(BACKGROUNDS, 1):
            print(f"\n├─ [{i}/{len(BACKGROUNDS)}] {bg[:40]}...")
            
            result = self.generate_variation(
                character,
                action=action,
                background=bg
            )
            
            if result:
                results.append(result)
            
            if i < len(BACKGROUNDS):
                time.sleep(delay_seconds)
        
        print(f"\n✓ Generated {len(results)}/{len(BACKGROUNDS)} background images")
        return results
    
    def generate_grid(
        self,
        character: CharacterProfile,
        actions: List[str] = None,
        backgrounds: List[str] = None,
        delay_seconds: float = 1.5
    ) -> List[Tuple[str, Path]]:
        """
        Generate GRID kombinasi: setiap action x setiap background.
        PERINGATAN: Bisa menghasilkan BANYAK gambar!
        
        Contoh: 5 actions x 5 backgrounds = 25 gambar
        
        Args:
            character: CharacterProfile object
            actions: List aksi (default: 5 aksi pertama)
            backgrounds: List background (default: 5 background pertama)
            delay_seconds: Delay antar request
        
        Returns:
            List of (URL, Path) tuples
        """
        import time
        
        # Default ke subset kecil
        action_list = actions or ACTIONS[:5]
        bg_list = backgrounds or BACKGROUNDS[:5]
        
        total = len(action_list) * len(bg_list)
        
        log.header(f"GRID GENERATION: {character.name}")
        print(f"│  Actions: {len(action_list)}")
        print(f"│  Backgrounds: {len(bg_list)}")
        print(f"│  TOTAL IMAGES: {total}")
        
        if not character.reference_image_url:
            log.error("No reference image!")
            return []
        
        results = []
        count = 0
        
        for action in action_list:
            for bg in bg_list:
                count += 1
                print(f"\n├─ [{count}/{total}]")
                log.info("Action", action[:40])
                log.info("Background", bg[:40])
                
                result = self.generate_variation(
                    character,
                    action=action,
                    background=bg
                )
                
                if result:
                    results.append(result)
                
                if count < total:
                    time.sleep(delay_seconds)
        
        print(f"\n✓ Generated {len(results)}/{total} grid images")
        return results


# ============================================================================
# INTERACTIVE MENU
# ============================================================================

def interactive_menu():
    """
    Menu interaktif untuk generate banyak gambar
    """
    print("""
╔═══════════════════════════════════════════════════════════╗
║       🎨 MASS CHARACTER IMAGE GENERATOR                    ║
║       Generate Unlimited Consistent Character Images       ║
╚═══════════════════════════════════════════════════════════╝
    """)
    
    gen = MassCharacterGenerator()
    
    # Check existing characters
    existing = gen.list_characters()
    
    if existing:
        print(f"\n📁 Found {len(existing)} existing character(s):")
        for i, char in enumerate(existing, 1):
            has_ref = "✓" if char.reference_image_url else "✗"
            print(f"   {i}. [{char.id}] {char.name} (ref: {has_ref})")
        
        print(f"\n   0. Create NEW character")
        
        try:
            choice = input("\nPilih nomor karakter (atau 0 untuk baru): ").strip()
            
            if choice == "0" or not choice:
                character = create_character_interactive(gen)
            else:
                idx = int(choice) - 1
                if 0 <= idx < len(existing):
                    character = existing[idx]
                    print(f"\n✓ Selected: {character.name}")
                else:
                    print("Invalid choice, creating new...")
                    character = create_character_interactive(gen)
        except:
            character = create_character_interactive(gen)
    else:
        print("\n📁 No existing characters found. Let's create one!")
        character = create_character_interactive(gen)
    
    if not character:
        print("❌ No character created. Exiting.")
        return
    
    # Check/generate reference
    if not character.reference_image_url:
        print("\n🎯 Generating reference image first...")
        ref = gen.generate_reference(character)
        if not ref:
            print("❌ Failed to generate reference. Check API.")
            return
    
    # Generation menu
    while True:
        print(f"""
╔═══════════════════════════════════════════════════════════╗
║  Character: {character.name[:40]:<40} ║
╚═══════════════════════════════════════════════════════════╝

📸 GENERATION OPTIONS:
   1. Generate random variations (specify count)
   2. Generate ALL actions (30 images)
   3. Generate ALL backgrounds (30 images)  
   4. Generate GRID (actions x backgrounds)
   5. Generate custom single image
   
   0. Exit
""")
        
        try:
            choice = input("Pilih opsi (1-5, atau 0 untuk exit): ").strip()
            
            if choice == "0":
                print("\n👋 Bye! Check your images in:", IMAGES_DIR)
                break
                
            elif choice == "1":
                count = int(input("Berapa gambar? (1-100): ").strip() or "10")
                count = min(max(1, count), 100)
                gen.generate_mass_variations(character, num_images=count)
                
            elif choice == "2":
                bg = input(f"Background (kosong = studio): ").strip()
                bg = bg or "clean white studio background"
                gen.generate_all_actions(character, background=bg)
                
            elif choice == "3":
                action = input(f"Action (kosong = standing): ").strip()
                action = action or "standing confidently"
                gen.generate_all_backgrounds(character, action=action)
                
            elif choice == "4":
                print("\n⚠️  GRID = Actions x Backgrounds")
                a = int(input("Jumlah actions (1-30): ").strip() or "5")
                b = int(input("Jumlah backgrounds (1-30): ").strip() or "5")
                a = min(max(1, a), 30)
                b = min(max(1, b), 30)
                print(f"\n🔢 Total gambar: {a * b}")
                confirm = input("Lanjutkan? (y/n): ").strip().lower()
                if confirm == 'y':
                    gen.generate_grid(character, actions=ACTIONS[:a], backgrounds=BACKGROUNDS[:b])
                    
            elif choice == "5":
                action = input("Action: ").strip()
                bg = input("Background: ").strip()
                emotion = input("Emotion (opsional): ").strip()
                
                gen.generate_variation(
                    character,
                    action=action or "standing",
                    background=bg or "simple background",
                    extra_details=emotion
                )
                
        except KeyboardInterrupt:
            print("\n\n👋 Interrupted. Bye!")
            break
        except Exception as e:
            print(f"\n❌ Error: {e}")
            continue


def create_character_interactive(gen: MassCharacterGenerator) -> Optional[CharacterProfile]:
    """Create character melalui input interaktif"""
    print("\n🆕 CREATE NEW CHARACTER")
    print("─" * 40)
    
    try:
        name = input("Nama karakter: ").strip()
        if not name:
            name = "My Character"
        
        print("\n📝 Tips: Jelaskan karakter sedetail mungkin!")
        description = input("Deskripsi umum (contoh: 'A cute cartoon cat'): ").strip()
        appearance = input("Penampilan (contoh: 'orange fur, blue eyes, fluffy tail'): ").strip()
        clothing = input("Pakaian (contoh: 'red hoodie, blue jeans'): ").strip()
        
        print("\nStyle contoh: '3D Pixar style', 'anime style', 'cartoon style', 'realistic'")
        style = input("Style gambar: ").strip()
        
        return gen.create_character(
            name=name,
            description=description or "A cute character",
            appearance=appearance or "colorful and expressive",
            clothing=clothing or "casual outfit",
            style=style or "high quality cartoon style"
        )
        
    except KeyboardInterrupt:
        return None


# ============================================================================
# QUICK COMMANDS
# ============================================================================

def quick_generate(num_images: int = 10):
    """Quick generate dengan karakter default"""
    gen = MassCharacterGenerator()
    
    # Create default character
    char = gen.create_character(
        name="Quick Character",
        description="A cute friendly mascot character",
        appearance="colorful appearance, big expressive eyes, friendly face",
        clothing="casual comfortable outfit",
        style="3D cartoon style, high quality, vibrant colors"
    )
    
    # Generate reference
    ref = gen.generate_reference(char)
    
    if ref:
        # Mass generate
        gen.generate_mass_variations(char, num_images=num_images)
    else:
        print("❌ Failed to generate reference")


# ============================================================================
# MAIN
# ============================================================================

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1:
        arg = sys.argv[1]
        
        if arg == "--interactive" or arg == "-i":
            interactive_menu()
            
        elif arg == "--quick":
            count = int(sys.argv[2]) if len(sys.argv) > 2 else 10
            quick_generate(count)
            
        elif arg == "--help" or arg == "-h":
            print("""
╔═══════════════════════════════════════════════════════════╗
║       🎨 CONSISTENT CHARACTER IMAGE GENERATOR              ║
╚═══════════════════════════════════════════════════════════╝

USAGE:
  python consistent_character_generator.py [OPTION]

OPTIONS:
  --interactive, -i    Menu interaktif (RECOMMENDED)
  --quick [N]          Quick generate N gambar (default: 10)
  --help, -h           Tampilkan bantuan ini

EXAMPLES:
  python consistent_character_generator.py -i          # Interactive menu
  python consistent_character_generator.py --quick 20  # Generate 20 images
  
IMPORT IN CODE:
  from consistent_character_generator import MassCharacterGenerator
  
  gen = MassCharacterGenerator()
  char = gen.create_character(...)
  gen.generate_reference(char)
  gen.generate_mass_variations(char, num_images=50)
  
PREDEFINED VARIATIONS:
  - 30 Actions (running, jumping, dancing, etc.)
  - 30 Backgrounds (park, beach, city, etc.)
  - 10 Emotions (happy, excited, calm, etc.)
  
  Maximum combinations: 30 x 30 x 10 = 9,000 unique images!
""")
        else:
            print(f"Unknown option: {arg}")
            print("Use --help for usage information")
    else:
        # Default: interactive menu
        interactive_menu()
